version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
  threat-intelligence:
    build: ./scripts
    command: python threat_intelligence.py

volumes:
  es_data:
